### ISSUE TITLE
remove Annotation options!

### ISSUE THREAD

**Issue by tkschmidt** [kusterlab/universal_spectrum_explorer#12]

**Comment by BenSamy2020** [comment]
Greetings,

I would like to thank you for providing this amazing open-source tool. 

By any chance had this feature been enabled and where do I find it? I would like to only download the mirror plot with matching peaks without peak labels. This reason is that when two peaks are close together the labels of both the peaks tend to overlap. Due to this I would rather download the image with highlighted matching peaks and label it myself later on. Alternatively, you may want to implement an improvement to prevent overlapping labels. 

Regards,
Ben.
